id: IBBC734E4
default_language: en-us
source: ''
initial_creation_type: tmx
imported: 2022-12-14 18:03:53.309041+00:00
last_modified: 2022-12-14 18:03:53.309046+00:00
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-061-016
  eft-text-version: 1.1.5 2020
  title: Toh_196-The_Dwelling_Place_of_Manjusri-v2
bases:
  DDEF:
    source_metadata: null
    order: 1
    base_file: DDEF.txt
    statistics: null
copyright:
  status: Unknown
  notice: ''
